name:                gostwriter
version:             0.1.0.0
github:              "popovvitaly/gostwriter"
license:             BSD3
author:              "Vitaly Popov"
maintainer:          "Vitaly Popov"
copyright:           "2022 Vitaly Popov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/popovvitaly/gostwriter#readme>

dependencies:
- base
- aeson
- http-api-data
- http-client
- http-client-tls
- mtl
- servant-client
- telegram-bot-simple
- text

executables:
  gostwriter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  gostwriter-test:
    main:                Spec.hs
    source-dirs:
    - test
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
